### ISSUE TITLE
Forgot password/Reset Password Page 

### ISSUE THREAD

**Issue by Stnagam** [Stnagam/Reitz-Union-Hotel-Management#30]
Acceptance Criteria:

1. User should land onto this page only after clicking Forget Password on the log in page 
2. Should be able to take in the user email as input(email format validation mandatory)
3. Should contain a button "Reset Password" right below the user email input 
4. Should display a note to the user stating them to "Check their email"
5. Should display a note to the user stating email does not exist if the email ID isn't present in the Database(Create the note for now database validation can be done  once the backend team supports the full functionality)

**Comment by harshapakki** [comment]
PR Raised
